# Generated by Django 4.0.3 on 2022-03-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0002_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in progress', 'In Progress'), ('under review', 'Under Review'), ('done', 'Done')], max_length=12),
        ),
    ]
