# Generated by Django 4.0.3 on 2022-03-12 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0005_task_status_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
